### ISSUE TITLE
Download search Result and Dashboard Values as CSV

### ISSUE THREAD

**Issue by mvonline** [chabokpush/chabok-panel#1]
Hi. 
Will be thankful if you add the possibility to download Dashboard value details (such as disabled user details, invalid tokens, removed devices, Users who have not returned to the system and etc)  and Search result as CSV or Provide official an API for getting those value. 
thanks a lot.

**Comment by behrad** [comment]
We sure will support CSV export in two types:

1. exporting specific chart values as CSV

2. exporting custom data as CSV

currently you can email us about the specific data you need, and we will help you out.

**Comment by behrad** [comment]
Shall we keep it open @mvonline ?
