### ISSUE TITLE
اتصال به چابک با موفقیت انجام شده اما همچنان پوش دریافت نمی شود

### ISSUE THREAD

**Issue by ehsan-dev** [chabokpush/chabok-panel#11]
سلام.. خسته نباشید...در کانفیگ اولیه پروژه اندرویدی ما اتصال به چابک صورت گرفته و کاربر در چابک ثبت نام می شود 
 اما همچنان پوش دریافت نمی شود... تمام نکاتی که مشخص کردید انجام شده.. خطایی هم در لاگ پیدا نیست.... آیا امکانش هست با انی دسک  بیاید رو سیستم ما و مشکل را بررسی کنید... هزینه این کار هم پرداخت می کنیم... ممنون

**Comment by Husseinhj** [comment]
<p dir="rtl">شما این موضوع را در issue #9  مطرح کرده‌اید. لطفا در همان issue کامنت خود را قرار دهید</p>
