### ISSUE TITLE
مشکل در نمایش وب پوش

### ISSUE THREAD

**Issue by kamrane** [chabokpush/chabok-panel#12]
توسط سرور پوش ارسال میشه 
سیستم شما دریافت میکنه
وضعیت پوش رو تحویل شده میزنه
اما پوش به کاربر نمیرسه

**Comment by kamrane** [comment]
آیا ServiceWorker مشکل داره؟

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">از انجایی که این issue در بخش نامرتبط قرار دارد من یک <a href="https://github.com/chabokpush/chabok-client-js/issues/16">issue</a> در بخش جاوا اسکریپت با این موضوع ایجاد کردم. لطفا مشکل را issue جدید دنبال کنین</p>

**Comment by kamrane** [comment]
خب شاید جاوا اسکریپت نباشه که با سرعت نور به اینجا منتقلش کردین!!!

**Comment by kamrane** [comment]
بین این همه ارسال ممکنه بعضی ها رو هم نشون بده!!!!!!!!!

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">طبق عنوان issue و موضوعی که مطرح کردین (وب پوش) و اشاره به <code>serviceWorker</code>  برداشت من این بود که این مشکل مربوط به اس‌دی‌کی جاوا اسکریپت هست</p>

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">لطفا مشکل خود را کامل تر  در صورت وجود خطا چه در اس‌دی‌کی و چه در پنل قسمت پیام‌ها قرار بدین تا بهتر راهنمایی کنیم.</p>
<p dir="rtl"> این مشکل را در <a href="https://github.com/chabokpush/chabok-client-js/issues/16">issue</a> دنبال کنین تا در صورتی که برنامه‌نویسان دیگر نیز با مشکل مشابهی مواجه شدن راحت تر به جواب برسن</p>
<p dir="rtl">با تشکر</p>

**Comment by kamrane** [comment]
کاربر ثبت شده
![1](https://user-images.githubusercontent.com/16122154/49367784-45551800-f702-11e8-9edd-db4994b938c6.png)

برای کاربر 2 تا دستگاه وجود داره
![3](https://user-images.githubusercontent.com/16122154/49367903-9bc25680-f702-11e8-9830-5c5fa1779e78.png)

پوش توسط api ارسال میشه
در بسیاری موارد پوش در هیچ دستگاهی نمایش داده نمیشه
و در سایر موارد فقط برای 1 دستگاه نمایش داده میشه

ولی در گزارش چیز دیگه ای نشون میده!!
![4](https://user-images.githubusercontent.com/16122154/49368142-37ec5d80-f703-11e8-9ec5-db63b84fc02e.png)

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">بر اساس تصویر صفحه پیام‌های شما. تنظیمات <code>service worker</code> شما به درستی انجام نشده به همین خاطر ارسال پوش نوتیفیکشین با خطا مواجه شده.
لطفا از نصب <code>service worker</code> و صحت اطلاعات <code>VAPID</code> در پنل و در کلاینت اطمینان حاصل فرمایید. برا مطالعه بیشتر لطفا به <a href="https://dev.doc.chabokpush.com/javascript/troubleshoot.html#%D9%85%D8%B1%D9%88%D8%B1%DA%AF%D8%B1-%D8%A8%D8%B3%D8%AA%D9%87-%D8%A7%D8%B3%D8%AA-%D9%88-%D9%BE%D9%88%D8%B4-%D9%86%D9%85%DB%8C%DA%AF%DB%8C%D8%B1%D9%85">بخش عیب‌یابی مستندات</a> مراجعه نمایید.</p>

<blockquote dir="rtl">
<p dir="rtl">ولی در گزارش چیز دیگه ای نشون میده!!</p>
</blockquote>
<p dir="rtl">تیک سبز موجود در گزارش به معنای تحویل پیام چابک هست و نه به معنی دریافت پوش نوتیفیکشین</p>
<blockquote dir="rtl">
<p dir="rtl">تاکید ما در دسته‌بندی issue ها، برای راحتی پیدا شدن مشکل‌های مشابه توسط برنامه‌نویسان دیگر است. لطفا  این مشکل را در بخش جاوا اسکریپت دنبال نمایید.</p>
</blockquote>

**Comment by kamrane** [comment]
> تیک سبز موجود در گزارش به معنای تحویل پیام چابک هست و نه به معنی دریافت پوش نوتیفیکشین

درست
اما مساله تاریخ تحویل هست
که تاریخ وجود دارد آما خود پوش نمایش داده نمی شود

و مهمتر اینکه با همه این تفاسیر برخی موارد پوش نمایش داده می شود!!!!!!!!!!!!!!!!!!

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">لطفا <strong>payload</strong> پوش ارسالی خود
به همراه کد مربوط به چابک در کلاینت را قرار بدین تا بررسی کنیم.</p>
