### ISSUE TITLE
شناسه یکسان چند دستگاه

### ISSUE THREAD

**Issue by kamalhoseini** [chabokpush/chabok-panel#15]
سلام، خدا قوت
مهندس ، در دریافت نوتیفیکیشن با چند دستگاه که شناسه دستگاه  برای انها یکسان است
مثلا : کروم موبایل و موزیلا دسکتاپ) ، دچار مشکل شدیم )
ایا ممکن است از، ای دی یکسان دستگاه ها باشد؟؟؟؟
متشکرم.

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">مثلا : کروم موبایل و موزیلا دسکتاپ) ، دچار مشکل شدیم )</p>
</blockquote>
<p dir="rtl">لطفا در مورد مشکلی که دارید بیشتر توضیح دهید. </p>
<p dir="rtl">آیا پوش‌نوتیفیکیشن دریافت نمی‌کنید؟</p>
<p dir="rtl">در کدام پلتفرم نوتیفیکیشن نمایش داده نمی‌شود؟</p>
<p dir="rtl">آیا روی آن پلتفرم VPN روشن بوده؟</p>
<p dir="rtl">در صورت رخ دادن خطا در دریافت نوتیفیکیشن، به پنل مراجعه کنید و در صفحه پیام‌ها خطایی که دستگاه با آن مواجه شده را اینجا قرار دهید</p>
<p dir="rtl">لطفا بخش عیب‌یابی <a href="https://doc.chabokpush.com/android/troubleshoot.html">اندروید</a>، <a href="https://doc.chabokpush.com/ios/troubleshoot.html">iOS</a> و <a href="https://doc.chabokpush.com/javascript/troubleshoot.html">وب‌پوش</a> بخش را مطالعه کنید</p>

**Comment by Husseinhj** [comment]
@kamalhoseini آیا مشکل شما حل شده است؟

**Comment by kamalhoseini** [comment]
سلام، با تشکر از پیگیری شما،
service worker جدید رو اضافه کردم ،حل شد.

‫‪Hussein Habibi Juybari‬‏ <‪notifications@github.com‬‏> در تاریخ یکشنبه ۶
ژانویهٔ ۲۰۱۹ ساعت ۱۰:۴۶ نوشت:‬

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">سلام، با تشکر از پیگیری شما،</p>
</blockquote>

<p dir="rtl">مرسی از پاسخ شما. من issue رو می‌بندم اگر مشکل مشابه داشتید می‌تونید issue رو باز کنید تا راهنماییتان کنیم</p>
