### ISSUE TITLE
gcm یا fcm

### ISSUE THREAD

**Issue by rahimasgari** [chabokpush/chabok-panel#17]
<p dir="rtl">با سلام و احترام</p>
<p dir="rtl">میخواستم بدون سرویس چابک از سرویس قدیمی گوگل یعنی جی سی ام استفاده میکنه یا اینکه از سرویس جدید اف سی ام استفاده میشه.
چون زمانی که در پنل چابک میخوام تنظیمات اندروید رو انجام بدم از من
 gcm api key و gcm sender id 
میخواد.</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">چابک از هر دو استفاده می‌کنه و اینکه چون اپلیکیشن‌های قدیمی‌ای داریم که هنوز رو GCM هستند چابک GCM رو هم هنوز ساپورت می‌کنه  ولی سرور چابک پیش‌فرض به FCM متصل هست و از senderId استفاده نمی‌کنه</p>
