### ISSUE TITLE
پیدا نشدن دستگاه کاربر برای دریافت پوش

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-panel#19]
سلام
وقتتون بخیر
تا چند روز پیش برای یک کاربر که پوش ارسال میکردیم بهش میرسید ولی الان به هرکاربری که میخوایم پوش بفرستیم تو پنل میزنه که دستگاه کاربر پیدا نشد و هیچ پوشی ارسال نمیشه
ایمیل من a.alian@shab.ir هستش
ممنون میشم بررسی کنید و دلیلش رو بهم بگید

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">تا چند روز پیش برای یک کاربر که پوش ارسال میکردیم بهش میرسید ولی الان به هرکاربری که میخوایم پوش بفرستیم تو پنل میزنه که دستگاه کاربر پیدا نشد و هیچ پوشی ارسال نمیشه</p>
</blockquote>
<p dir="rtl">حساب شمارو بررسی کردیم و شما از تاریخ ۶ دی ماه فقط دارین به یک <code>userId</code> <strong dir="rtl">ثابت</strong> پیام ارسال می‌کنین که این دستگاه از پنل حذف شده به همین جهت خطای<code>device not found</code> در پنل نمایش داده میشه</p>
<p dir="rtl">اگر از پنل وارد بخش پیام‌ها و تب پیام‌ها بشید، می‌تونید ریز پیام‌های ارسالی خودتون رو ببینید که فقط به یک کاربر بوده</p>
<p dir="rtl">شما از تاریخ <strong dir="rtl">۳۰ دی ساعت ۱۴:۲۳:۵۴</strong> پوش دریافت می‌کردید ولی در تاریخ <strong dir="rtl">۱ بهمن ۱۲:۲۸:۱۹</strong> توکن این کاربر با خطا مواجه شده و بعد با خطای نامعتبر بودن توکن، چابک در تاریخ <strong dir="rtl">۳ بهمن ساعت ۱۴:۴۶:۰۴</strong> دستگاه رو پاک کرده </p>
