### ISSUE TITLE
Search by user id not work in panel

### ISSUE THREAD

**Issue by Mehrdad-Dadkhah** [chabokpush/chabok-panel#2]
Hi
Search by user id not work in panel.
please check it

tnx

**Comment by jangholi** [comment]
It will be fixed in the next version

**Comment by Mehrdad-Dadkhah** [comment]
When is your release?
We need it to check some problems and it's very necessary for us

**Comment by Husseinhj** [comment]
<p dir="rtl">@Mehrdad-Dadkhah 
شما می‌تونین با استفاده از گزینه جستجو شناسه اقدام به جستجو نام‌کاربری کنین فعلا :</p>
<p dir="rtl"><img src="https://user-images.githubusercontent.com/27139702/45618419-cb11e180-ba8a-11e8-9e85-6b2d067bbde2.png" alt="image"></p>

**Comment by jangholi** [comment]
@Mehrdad-Dadkhah This issue has been resolved.
