### ISSUE TITLE
devices list

### ISSUE THREAD

**Issue by kalantari96** [chabokpush/chabok-panel#20]
salam
tu oneSignal mishod ba api liste tamame device ha ya yek device moshakhas ro gereft, hamchin emkani tu chabok vujud dare?

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">liste tamame device ha</p>
</blockquote>
<p dir="rtl">بخاطر مسائل  امنیتی این api در دسترس نیست.</p>
<blockquote dir="rtl">
<p dir="rtl">yek device moshakhas ro gereft</p>
</blockquote>
<p dir="rtl">شما می‌تونین <a href="https://api.doc.chabokpush.com/#/installation/installation_fetchById">لیست دستگاه‌های یک userId</a> رو دریافت کنین</p>
<p dir="rtl">و یا می‌تونین <a href="https://api.doc.chabokpush.com/#/installation/installation_fetchByUserId">اطلاعات یک دستگاه مشخص</a> رو دریافت کنین</p>

**Comment by kalantari96** [comment]
ahan doroste, mamnun az rahnamayitun
historye notificationaye ersaliyam nadarim,na?

**Comment by Husseinhj** [comment]
> historye notificationaye ersaliyam nadarim,na?

<p dir="rtl">خیر،‌ این موضوع هم بخاطر مسائل امنیتی در دسترس نیست.</p>
<p dir="rtl">اگه نیازتون رو دقیقا به ما بگین، می‌تونیم بهتر راهنماییتون کنیم. می‌تونین با <a href="https://doc.chabokpush.com/panel/settings.html#%D9%88%D8%A8-%D9%87%D9%88%DA%A9">وب هوک پیام‌های تحویل شده</a> رو دریافت کنین</p>

**Comment by kalantari96** [comment]
bebinin man mikham tu panelam in emkanato dashte basham, chon content manageram k nemitune hardafe biad tu dashboarde chabok, mikham yejuri bashe k tu panele khodemun hameye userayi k subscribe kardan ye listi azashun dashte basham harvaght khastam be ye usere khas betunam notif bedam

**Comment by behrad** [comment]
اگر شما هدف‌تون ایجاد یک پنل مجزا برای استفاده از چابک هست این کار با خرید وب‌سرویس‌های خصوصی چابک برای شما امکان پذیر هست اما هزینه زمانی برنامه نویسی و توسعه برای خودتون داره
اگر منظورتون رو درست متوجه شدیم لطفن درخواست یک جلسه کنید تا حضوری بهتر راهنمایی کنیم
اگر نیازتون رو متوجه نشدیم لطفن جزییات بیشتری اینجا یا در ایمیل یا تلفن به ما بدید

**Comment by kalantari96** [comment]
لطف می کنین یه شماره تماس بهم بدین؟

**Comment by behrad** [comment]
در سایت اطلاعات تماس موجود هست

https://chabokpush.com
