### ISSUE TITLE
ارتقا به پنل عملیاتی

### ISSUE THREAD

**Issue by shdehnavi** [chabokpush/chabok-panel#22]
سلام
آیا امکانش هست که اپلیکیشن رو بدون اینکه نسخه عملیاتی رو خریده باشیم انتشار دهیم و پس از چندماه نسخه عملیاتی رو خریداری کنیم ؟
یعنی با خرید نسخه عملیاتی، مشکلی در سرویس های قبلی پیش نمیاد و فقط ارتقای سرویس انجام میشه؟ و سرویس پوش اپ با مشکل مواجه نمیشه؟

**Comment by behrad** [comment]
سلام
امکانش هست بله اما توجه داشته باشید که
۱. نسخه رایگان تعهد و پشتیبانی در قبال هیچ موردی برای اپلیکیشن شما نخواهد داشت
۲. تعداد کاربر روزانه محدود میشه به سقف ۵۰۰ کاربر
۳. اکانت عملیاتی جدا هست از اکانت رایگان و شما مجبور خواهید بود اپلیکیشن رو آپدیت بدید 
۴. دیتای شما به طور پیش فرض منتقل نمیشه به حساب عملیاتی و در صورت نیاز به مهاجرت دیتا باید هزینش رو پرداخت کنید

در نهایت، اگر اپلیکیشن شما تجاری شده و الان دست کاربر به طور جدی داره کار می کنه توصیه می کنیم عملیاتی را استفاده کنید
اما اگر اپلیکیشن شما خیلی تازه وارد هست و هنوز در اولین مراحل انتشار هست، نسخه رایگان رو تا مرحله تجاری سازی جدی تر استفاده کنید

امیدوارم شفاف بوده باشه
