### ISSUE TITLE
مشکل در هنگام ورود

### ISSUE THREAD

**Issue by mehdi-mashayekhi** [chabokpush/chabok-panel#24]
سلام و درود
ما همیشه موقع ورود به چابک مشکل داریم
یعنی برای اولین بار که کش نکرده سایت رو هنوز
امروز دیگه خسته شدم و اومدم ببینم واقعا مشکل چیه
وقتی میخوایم وارد حساب بشیم
https://sandbox.push.adpdigital.com/login

https://rawgit.com/jeanlescure/short-unique-id/master/dist/short-unique-id.min.js
این فایل اصلا دانلود نمیشه

همش در انتظار میمونه
الان که با شما صحبت میکنم نزدیک به 3 دقیقه هست هیچ اتفاقی نیافتاده
یادمه از چند ماه پیش خیلی وقتا این اتفاق برای من موقع ورود میافته و من هیچ کاری نمیتونم انجام بدم

مشایخی تیم ایران ضایعات این مورد را قبلا هم گفته بودم اما رسیدگی نشد و جوابی که به من داده شد این بود که خب صفحه سنگین هست یا اینکه یبار هرطوری که هست وارد بشم تا مشکل رفع بشه

**Comment by behrad** [comment]
> ما همیشه موقع ورود به چابک مشکل داریم

تا ۲ ماه پیش حجم دانلود زمان بارگذاری صفحه اول پنل زیاد بود که اون رو کم کردیم
و بعضی کاربرا درزمان اتصال به وی‌پی‌ان مشکل داشتند  و بعد از اون ماجرا مشکل حل شد



> این فایل اصلا دانلود نمیشه

مرسی از دقت شما و کمکی که در گزارش این مشکل به ما کردین
گویا این فایل روی گیت‌هاب بدون وی پی ان در دسترس نیست برای کاربران ایرانی و این اتفاق اخیرن افتاده
بچه‌ها این مشکل رو ظهر امروز برطرف کردند

شما از ظهر امروز نباید مشکلی در لاگین به پنل داشته باشید
اگر مشکلی داشتید حتمن گزارش کنید وظیفه ماست اصلاح کنیم
