### ISSUE TITLE
دلیل صف طولانی در انتظار تحویل چیست؟

### ISSUE THREAD

**Issue by Phessami** [chabokpush/chabok-panel#28]
<p dir="rtl">سلام، </p>
<p dir="rtl">دیروز از طریق پنل تعداد ۱۶,۶۵۷ پیام پوش برای کاربرانمان ارسال کردیم که تنها 734 عدد از این پیام‌ها تا این لحظه تحویل کاربر داده شده است.
دلیل صف بسیار طولانی ارسال پیام چیست؟ اگر پیام مورد نظر در همان لحظه به کاربر نرسد ارزشش را از دست خواهد داد.</p>
<p dir="rtl">یک عکس از پنل روخدمتتون ارسال کرده‌ام</p>
<p dir="rtl"><img src="https://user-images.githubusercontent.com/34546380/56110113-8854b100-5f68-11e9-9096-5a48c88122af.JPG" alt="chabok panel"></p>

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">دلیل صف طولانی در انتظار تحویل چیست؟</p>
</blockquote>
<p dir="rtl"> کاربرا هنوز اپلیکیشن‌تون رو <strong dir="rtl">باز نکردن</strong> تا <a href="https://doc.chabokpush.com/panel/dashboard.html#%D9%BE%DB%8C%D8%A7%D9%85%D9%87%D8%A7"><strong dir="rtl">پیام چابک</strong></a> رو دریافت کنن.</p>
<hr>
<blockquote dir="rtl">
<p dir="rtl">تنها 734 عدد از این پیام‌ها تا این لحظه تحویل کاربر داده شده است</p>
</blockquote>
<p dir="rtl">تحویل پیام در واقع نمودار <strong dir="rtl">بازگشت</strong> (<strong>retention</strong>) اپلیکیشن‌تون رو نشون میده که عوامل زیادی در افزایش بازگشت کاربرا تاثیر گذار هست، مثل <strong dir="rtl">زمان ارسال</strong>، نوع محتوا ارسال شده (<strong dir="rtl">محتوا شخصی‌سازی شده بر اساس رفتار کاربر</strong> یا <strong dir="rtl">محتوا عمومی</strong>)  و ...</p>
<blockquote dir="rtl">
<p dir="rtl">دلیل صف بسیار طولانی ارسال پیام چیست؟</p>
</blockquote>
<p dir="rtl"><strong dir="rtl">در صف</strong>، به این معنی هست که کاربر اپلیکیشن رو <em dir="rtl">باز نکرده</em> تا پیام رو <strong dir="rtl">دریافت کنه</strong> و زمانی که اپلیکیشن رو باز کنه، از صف خارج میشه و پیام به اون تحویل داده میشه.</p>
<p dir="rtl"><strong dir="rtl">تحویل شده</strong>، به این معنی هست که کاربرها <em dir="rtl">اپلیکیشن رو باز کردن</em> و یا موقع ارسال پیام <em dir="rtl">اپلیکیشن‌شون باز بوده</em> و <strong dir="rtl">پیام بهشون تحویل داده شده</strong>.</p>
<p dir="rtl">اسم این قابلیت <strong dir="rtl">صندوق پیام چابک</strong> هست که نحوه عملکرد اون به این شکل هست:</p>
<p dir="rtl">چابک برای ارسال پیام هنگامی که کاربر به <strong dir="rtl">سرور چابک متصل</strong> است (<em dir="rtl">باز بودن اپلیکیشن</em>) از سرویس آنی خود استفاده می‌کند (<strong dir="rtl">پیام چابک</strong>) و در صورت <strong dir="rtl">عدم اتصال به چابک</strong> (<em dir="rtl">بسته بودن اپلیکیشن</em>) اقدام به ارسال <strong dir="rtl">پوش‌نوتیفیکیشن</strong> می‌کند تا کاربر را از داشتن پیام چابک مطلع سازد</p>
<hr>
<blockquote dir="rtl">
<p dir="rtl">اگر پیام مورد نظر در همان لحظه به کاربر نرسد ارزشش را از دست خواهد داد.</p>
</blockquote>
<p dir="rtl">اگه به نمودار اعلان دقت کنین، ۶,۹۷۸ پوش‌نوتیفیکیشن <strong dir="rtl">با موفقیت به FCM داده شده</strong> (پلتفرم‌های FCM، APNs و WNS تحویل پوش‌نوتیفیکیشن به اپلیکیشن رو اعلام نمی‌کنن و در همه سرویس‌های پوش‌نوتیفیکیشن، تحویل پوش‌نوتیفیکیشن به این معنی هست که با موفقیت پوش شما به پلتفرم FCM،  APNS و WNS تحویل داده شده)، و این تعداد اعلان به موفقیت به FCM تحویل داده شده، اما <strong dir="rtl">نمودار تحویل پیام</strong> به این معنی هست که <strong dir="rtl">چه تعداد کاربر اپ رو باز کردن و پیام بهشون تحویل داده شده</strong>.</p>
<p dir="rtl">اگر می‌خواین ببینین که نمودار تحویل پیام منطقی هست یا خیر، لطفا با <strong dir="rtl">کاربران فعال روزانه (DAU)</strong> اپلیکیشن‌تون مقایسه کنین و توی داشبورد ببینین تو این بازه زمانی‌ که پیام رو ارسال کردین با توجه به <em dir="rtl">کاربران فعال روزانه</em> و <em dir="rtl">فیلتر پلتفرم اندروید</em>، آیا این عدد منطقی هست یا خیر؟</p>
<p dir="rtl">شما می‌تونین توی داشبورد در نمودار تحویل پیام، تحویل روزانه‌اتون رو ببینین (فیلتر <strong dir="rtl">درصف</strong> و <strong dir="rtl">رد شده</strong> رو خاموش کنین) و با هم مقایسه کنین </p>
<p dir="rtl">اگه نیاز به توضیح بیشتری دارین می‌تونین به <a href="https://chabokpush.com/contact.html">پشتیبانی تماس بگیرید</a> تا بیشتر راهنمایی‌تون کنیم</p>

**Comment by Phessami** [comment]
<p dir="rtl">تشکر بابت پاسخ کاملتون</p>
<p dir="rtl">بسیاری از موارد الان شفاف‌تر شد، اما یک مشکل هنوز پا برحاست. من توی شرکت از ۱۰ نفر از همکارام پرسیدم و بیرون شرکت هم از ۱۰ نفر. هیچ کدام پوش را دریافت نکرده بودند!</p>
<p dir="rtl">یعنی شما می‌فرمایید که مشکل ارسال پوش از سمت FCM بوده است؟</p>

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">تشکر بابت پاسخ کاملتون</p>
</blockquote>
<p dir="rtl">خواهش می‌کنم 👍 </p>
<blockquote dir="rtl">
<p dir="rtl">بسیاری از موارد الان شفاف‌تر شد، اما یک مشکل هنوز پا برحاست. من توی شرکت از ۱۰ نفر از همکارام پرسیدم و بیرون شرکت هم از ۱۰ نفر. هیچ کدام پوش را دریافت نکرده بودند!</p>
</blockquote>
<p dir="rtl">لطفا نام کاربری کسایی که میگین پوش نگرفتن رو توی پنل جستجو کنین و لیست اون‌ها رو به ایمیل پشتیبانی ما ارسال کنین تا دقیق‌تر راهنمایی‌تون کنیم که علت عدم دریافت پوش‌نوتیفیکیشن برای اون‌ها چی بوده.</p>

**Comment by Phessami** [comment]
حتما چند مورد رو خدمتتون ارسال می‌کنم:

34ade8301183488da1751cf3413a88b1
79b656b8d5ac4ede9ba1b81756634295
153c72c1cf884c56b1102cf9a0d7cf56

این کاربران مشکلی در دریافت نوتیف دارند و از کاربران فعال برنامه هستند. اما هیچ کدام پوش دست جمعی را دریافت نکردند.

شناسه رهگیری کمپین هم در زیر کپی می‌کنم:

jibimo-1398-1-25-18-7

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">این کاربران مشکلی در دریافت نوتیف دارند و از کاربران فعال برنامه هستند. اما هیچ کدام پوش دست جمعی را دریافت نکردند.</p>
<p dir="rtl">34ade8301183488da1751cf3413a88b1</p>
<p dir="rtl">79b656b8d5ac4ede9ba1b81756634295</p>
<p dir="rtl">153c72c1cf884c56b1102cf9a0d7cf56</p>
</blockquote>
<p dir="rtl">با بررسی این ۳ نام کاربری، متوجه شدیم که پوشی که ارسال کردین به سگمنتی با شرط زیر بوده:</p>
<p dir="rtl"><em dir="rtl">دستگاه</em> : <strong dir="rtl">اندروید</strong></p>
<p dir="rtl"><em dir="rtl">نسخه اپلیکیشن</em>:‌ <strong dir="rtl">کوچکتر از ۱.۶.۰</strong></p>
<p dir="rtl">تصویر سگمنتی که به اون پوش ارسال کردین:</p>
<p dir="rtl"><img src="https://user-images.githubusercontent.com/27139702/56125353-f9f32600-5f8d-11e9-9d24-36cef41dee6c.png" alt="image"></p>
<p dir="rtl">این 3 نام کاربری هر 3 نسخه <strong dir="rtl">۱.۶.۰</strong> رو داشتن و جزء سگمنتی که به اون پوش  ارسال کردین قرار نمی‌گیرن. چون شرطی که شما برای این سگمنت انتخاب کردین برای <strong dir="rtl">کوچکتر</strong> از این نسخه بوده و <strong dir="rtl">نه کوچکتر مساوی.</strong></p>
