### ISSUE TITLE
خطا هنگام درخواست حساب عملیاتی

### ISSUE THREAD

**Issue by mohammadTaghy** [chabokpush/chabok-panel#3]
سلام 
هنگام درخواست حساب عملیاتی می گوید خطایی رخ داده
نمیدونم چیکار کنم.درخواست راهنمایی دارم
با سپاس

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">@mohammadTaghy مشکل برطرف شد</p>

**Comment by mohammadTaghy** [comment]
با سپاس

**Comment by mohammadTaghy** [comment]
سلام
من درخواست دادم .حالا چطوری باید بفهمم که عملیاتی شده؟

**Comment by behrad** [comment]
> من درخواست دادم .حالا چطوری باید بفهمم که عملیاتی شده؟

هفته بعد با شما تماس گرفته میشه و بعد از مشخص شدن جزییات درخواست شما براتون اکانت عملیاتی تعریف میکنیم

**Comment by mohammadTaghy** [comment]
بسیار ممنون.
اما من ۲روز اپلیکیشن رو روی مایکت سیب اپ گذاشتم و نمیدونستم حساب باید
عملیاتی شود.امکانش هست اولویت من را بالاتر قرار دهید؟

**Comment by behrad** [comment]
در واقع یعنی شما با حساب سندباکس اپ خودتون رو روی استور گذاشتید؟

**Comment by mohammadTaghy** [comment]
بله.دقیقا.
و دیدیدم که نوتیف نمیاد.
بعد پرس و جو متوجه این موضوع شدیم.

**Comment by behrad** [comment]
نوتیف رو می تونید با تنظیماتتون توی پنل بررسی و درست کنید
پنل سندباکس چابک تا هزار کاربر در روز برای شما سرویس میده
شنبه صبح مورد شما رو پیگیری میکنیم باهاتون

**Comment by mohammadTaghy** [comment]
بسیار سپاسگذارم

**Comment by mohammadTaghy** [comment]
سلام.وقت بخیر
خوبید؟
برای عملیاتی کردن نام کاری درخواست دادم گفتید امروز باهام تماس
میگیرید.ممنون میشم پیگیری کنید.چون اپلیکیشن در مارکت سیب اپ است.
با سپاس.
