### ISSUE TITLE
اپلیکیشن جدید

### ISSUE THREAD

**Issue by sepehr13494** [chabokpush/chabok-panel#30]
با سلام آیا میشه روی یک اکانت 2 تا اپلیکیشن پیاده سازی کرد؟

**Comment by behrad** [comment]
اگر منظورتون دو اپلیکیشن مجزاست نخیر، دو اکانت باز کنید برای این منظور
البته بعدن این دو اکانت رو میشه بهم متصلشون کرد

**Comment by sepehr13494** [comment]
خب الان من چجوری با 1 ایمیل 2 تا اکانت باز کنم؟

**Comment by behrad** [comment]
در حال حاضر با ۲ ایمیل متفاوت اکانت باز کنید لطفا
در یکی دو ماه آینده این دو اکانت بهم متصل می شوند تا بتوانید با یک ایمیل از آنها استفاده کنید

**Comment by sepehr13494** [comment]
ممنون
