### ISSUE TITLE
نمونه کد برای asp.net core

### ISSUE THREAD

**Issue by hoseinjamshidi** [chabokpush/chabok-panel#33]
سلام وقت بخیر
برای پیاده سازی Api در asp.net core نیاز به نمونه کد داریم ممنون میشم روی سایت قرار بدید یا یک داکیومنت که به صورت ساده تر روش کار بیان کرده قرار بدید

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">سلام</p>
<p dir="rtl">راهنمای استفاده از Rest API در این <a href="https://doc.chabokpush.com/rest-api/guide.html">قسمت</a> بیان شده</p>
<p dir="rtl">همچنین <a href="https://api.doc.chabokpush.com/">Swagger</a> ما هم در دسترس هست 
براتون که میتونین payload درخواست ها و مثال‌هاش رو مشاهده کنین</p>

**Comment by hoseinjamshidi** [comment]
ممنون
