### ISSUE TITLE
ارسال نوتیفیکیشن به صورت تکی

### ISSUE THREAD

**Issue by hoseinjamshidi** [chabokpush/chabok-panel#34]
سلام وقت بخیر برای ارسال نوتیفیکیشن به صورت تکی کد مربوط بهکاربر مورد نظر باید در چه فیلدی قرار بدیم؟؟؟

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">سلام
جهت استفاده از API <code>toUsers</code> شناسه کاربر را در فیلد <code>user</code> قرار بدین</p>
<p dir="rtl">جهت اشنایی بیشتر با این API به این <a href="https://doc.chabokpush.com/rest-api/send-push.html#%D8%A7%D8%B1%D8%B3%D8%A7%D9%84-%D8%B4%D8%AE%D8%B5%DB%8C-%D9%BE%DB%8C%D8%A7%D9%85-%DA%86%D8%A7%D8%A8%DA%A9">قسمت از مستندات</a> رجوع نمایید</p>

**Comment by hoseinjamshidi** [comment]
ممنون فقط برای ارسال گروهی باید در فیلد user چه چیزی باید قرار بدم؟

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">برای ارسال گروهی باید از API <code>byQuery</code> استفاده کنین که در این API کلید <code>user</code> کاربردی ندارد و باید با استفاده از کلید <code>target</code> گروه رو مشخص کنین</p>
<p dir="rtl">به عنوان مثال، ارسال گروهی به کاربران اندروید:</p>
<pre><code>...
"target": {
  "deviceType": "android"
}
...</code></pre><p dir="rtl">برای مطالعه بیشتر به این <a href="https://doc.chabokpush.com/rest-api/send-push.html#%D8%A7%D8%B1%D8%B3%D8%A7%D9%84-%DA%AF%D8%B1%D9%88%D9%87%DB%8C">بخش از مستندات</a> مراجعه کنین</p>

**Comment by hoseinjamshidi** [comment]
ممنون
