### ISSUE TITLE
عدم دریافت ایمیل اعتبار سنجی 

### ISSUE THREAD

**Issue by aminsadeghipour** [chabokpush/chabok-panel#37]
<p dir="rtl">طبق اطلاعات این صفحه اقدام به اعتبار سنجی یوزرنیم کاربر میکنم. 
فراخوانی میشود اما ایمیلی به کاربر ارسال نمیشود.علت چیست؟ onsuccess  متد</p>

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">طبق اطلاعات این صفحه اقدام به اعتبار سنجی یوزرنیم کاربر میکنم. فراخوانی میشود اما ایمیلی به کاربر ارسال نمیشود.علت چیست؟ onsuccess متد</p>
</blockquote>
<p dir="rtl">کانکتور ایمیل برای حساب کاربری‌تون فعال نیست، لطفا این درخواست رو به ایمیل <a href="mailto:info@chabok.io">info@chabok.io</a> بزنین.</p>
<blockquote dir="rtl">
<p dir="rtl"><code>نکته</code>: اضافه کردن کانکتور ایمیل فقط برای <a href="https://doc.chabokpush.com/panel/settings.html#%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D8%AD%D8%B3%D8%A7%D8%A8-%D8%B9%D9%85%D9%84%DB%8C%D8%A7%D8%AA%DB%8C">حساب‌های عملیاتی</a> امکان پذیر هست.</p>
</blockquote>
