### ISSUE TITLE
مقدار دهی

### ISSUE THREAD

**Issue by hoseinjamshidi** [chabokpush/chabok-panel#38]
سلام وقت بخیز
برای ارسال داده به api سرایند فایل باید به چه صورت باشه؟
(Authoriza و Content-Type)

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">سلام</p>
<p dir="rtl">مقدار <code>Content-Type</code> را <code>application/json</code>
 و برای <code>Authorize</code> هم میتوانید با استفاده از query parameter <code>access_token</code> و یا در قسمت هدر <code>X-Access-Token</code> آن را فراهم بیاورید</p>

**Comment by hoseinjamshidi** [comment]
ممنون از راهنمایی شما
