### ISSUE TITLE
نشان دادن مقدار قبلی پیام خوش آمد

### ISSUE THREAD

**Issue by aminsadeghipour** [chabokpush/chabok-panel#39]
مقدار  پیام خوش آمد را در پنل چابک تغییر داده ام اما کماکان کاربران جدید  پیام پیشفرض با مقدار زیر را دریافت میکنند.:
به - خوش آمدید.
علت چیست؟
library:  chabok-lib-geo:2.17.1
account: free

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">سلام</p>
<p dir="rtl">مقدار پیام خوش‌آمد کش می‌شود و تا اعمال تغییر کمی زمان میبرد، که مدت این زمان را برای حساب‌های سندباکس کاهش دادیم و از این پس این مورد را مشاهده نخواهید کرد</p>
