### ISSUE TITLE
درخواست حساب عملیاتی

### ISSUE THREAD

**Issue by mohammadTaghy** [chabokpush/chabok-panel#4]
با سلام
درخواست حساب عملیاتی کردم.
می خواستم ببینم ثبت شده و چه میزان زمان خواهد برد برای عملیاتی کردن حساب؟

**Comment by behrad** [comment]
درخواست‌های حساب عمملیاتی ظرف ۲۴ ساعت اداری از زمان درخواست به ایجاد حساب منجر خواهند شد
لطفن ایمیلی که برای اون درخواست داده اید رو بررسی کنید اگر دریافت نکرده بودید برای ما یک ایمیل بزنید با همون ایمیل

**Comment by mohammadTaghy** [comment]
بله ایجاد شده
بسیار سپاسگذارم
