### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by hoseinjamshidi** [chabokpush/chabok-panel#41]
<p dir="rtl">سلام وقت بخیر زمان ارسال اطلاعات به API با ارور Internal Server Error روبرو میشوم
برای رفع این مشکل چه راه حلی وجود دارد؟</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">لطفا بفرمایید چه apiای رو کال می‌کنین؟</p>
<p dir="rtl"> CURL رو برامون اینجا قرار بدین</p>

**Comment by hoseinjamshidi** [comment]
<p dir="rtl">برای ارسال تکی نوتیفیکیشن از </p>
<pre><code>curl -X POST \
&quot;https://sandbox.push.adpdigital.com/api/push/toUsers?access_token=&lt;ACCESS_TOKEN&gt;&quot; \
-H &quot;accept: application/json&quot; \
-H &quot;Content-Type: application/json&quot; \
-d &quot;{ \&quot;user\&quot;: \&quot;Test\&quot;, \&quot;content\&quot;: \&quot;پرواز شما دچار نیم ساعت تاخیر شده است.\&quot;, \&quot;useAsAlert\&quot;: true}&quot;</code></pre><p dir="rtl">استفاده میکنم</p>

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">CURL داده شده صحیح می‌باشد</p>
<p dir="rtl">لطفا appId خود را اعلام نمایید تا بیشتر بررسی کنیم</p>

**Comment by hoseinjamshidi** [comment]
مشکل از سمت سیستم نرم افزاری خود ما بود
ممنون

**Comment by Husseinhj** [comment]
<p dir="rtl">مرسی که اطلاع دادید، پس من این issue رو close می‌کنم. اگر مشکل مشابهی مشاهده کردین، issue رو مجددا باز کنین و یک نمونه curl برامون قرار بدین تا بررسی‌های لازم رو انجام بدیم</p>

**Comment by hoseinjamshidi** [comment]
سلام و درود مجدد
مشکل کنونی ما این هست که از طریق یک api اطلاعات برای api شما ارسال میکنیم و با Internal Server Error روبرو شدیم
راه حل چیست؟

**Comment by behrad** [comment]
> مشکل کنونی ما این هست که از طریق یک api اطلاعات برای api شما ارسال میکنیم و با Internal Server Error روبرو شدیم
> راه حل چیست؟

لطفن ادرس و داده‌ارسالی و پاسخ دریافتی را عینن برای ما کپی کنید اینجا
اگر به فرمت CURL باشد که چه بهتر

**Comment by hoseinjamshidi** [comment]
این curl هست که به api خود ما مربوط میشه
curl -X POST "https://localhost:44390/api/consulation/Block-User-Whis-Moshir-For-User?userid=44" -H  "accept: application/json"

درون این api عملیات مورد نظر انجام میشه و api شما فراخوانی میشود
ارور
"Object reference not set to an instance of an object."

**Comment by hoseinjamshidi** [comment]
پارامت های کلاس انتقالی به api شما دقبیقا بر اساس https://api.doc.chabokpush.com/#/push/push_toUsers ایجاد شده و برخی از مقادیر مقدار دهی میشوئ

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">همانطور که مطرح کردین این curl مربوط به api شما می‌باشد</p>
<p dir="rtl">و با جستجوی خطای داده شده من متوجه شدم که این خطا به .Net مربوط میشود که احتمالا برای سرور شماست.</p>
<p dir="rtl"><a href="https://stackoverflow.com/questions/779091/what-does-object-reference-not-set-to-an-instance-of-an-object-mean">راه‌حل مطرح شده در stackoverflow</a></p>

**Comment by hoseinjamshidi** [comment]
ممنون

**Comment by hoseinjamshidi** [comment]
سوال اخر این که تمام پارامترهای مربوط به  https://api.doc.chabokpush.com/#/push/push_toUsers  در زمان فراخوانی باید مقدار دهی بشن؟؟

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">خیر</p>
<p dir="rtl">برای مشاهده فیلد‌های اجباری </p>
<p><img src="https://user-images.githubusercontent.com/14129756/61355331-616c8a80-a889-11e9-8ce9-d165ce4b2b7b.png" alt="image"></p>
<p dir="rtl">بر روی تب Model رفته و فیلد‌هایی که با ستاره مشخص شده‌اند اجباری می‌باشند</p>

**Comment by hoseinjamshidi** [comment]
ممنون از راهنمایی خوبتون
