### ISSUE TITLE
StatusCode: 400

### ISSUE THREAD

**Issue by hoseinjamshidi** [chabokpush/chabok-panel#45]
سلام وقت بخیر زمان فراخوانی api با ارور 400 رو به رو شدم
راه حل این مشکل چیه؟(در سیستم ما api شما از  طریق یک Api فراخوانی میشود)
user در api شما هر مقداری میتونه باشه؟؟(مثلا شماره موبایل کاربر)یا باید از طریق سیستم شما شناسه به اون اختصاص داده بشه؟

**Comment by hoseinjamshidi** [comment]
کد فراخوانی api شما
  using (var httpClient = new HttpClient())
            {
                using (var request = new HttpRequestMessage(new HttpMethod("POST"),"https://sandbox.push.adpdigital.com/api/push/toUsers?access_token=XXXXXX"))
                {
                    var myObject = new ChabokAllUsers();
.
.
.  
                  string jsonString = Newtonsoft.Json.JsonConvert.SerializeObject(myObject);
                    
                    request.Headers.TryAddWithoutValidation("Accept", "application/json");

                    request.Content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    var response = await httpClient.SendAsync(request);
                    return response;
                }
            }

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">سلام</p>
<p dir="rtl">لطفا payload ارسالی رو ضمیمه کنین تا بررسی کنم</p>

<blockquote dir="rtl">
<p dir="rtl">user در api شما هر مقداری میتونه باشه؟؟(مثلا شماره موبایل کاربر)یا باید از طریق سیستم شما شناسه به اون اختصاص داده بشه؟</p>
</blockquote>
<p dir="rtl">مقدار <code>user</code> همان شناسه کاربر هست که از طریق شما در سیستم چابک ثبت می‌شود</p>

**Comment by hoseinjamshidi** [comment]
ChabokNotificationPayload payload = new ChabokNotificationPayload();
                payload.notificationtitle = title;
                payload.body = captions;

                ChabokNotificationActions actions = new ChabokNotificationActions();
                actions.Id = "string";
                actions.Title = title; ;

                ChabokFallback fallback = new ChabokFallback();
                fallback.content = "string";
                fallback.delay = 0;
                fallback.media = "sms";

                ChabokSpecificUsers SpecificUsersFordAdvsr = new ChabokSpecificUsers();
                SpecificUsersFordAdvsr.user = AppId;
                SpecificUsersFordAdvsr.Content = captions;
                SpecificUsersFordAdvsr.channel = "default";
                SpecificUsersFordAdvsr.Myfallback = fallback;
                SpecificUsersFordAdvsr.ChabokNotificationPayload = payload;
                SpecificUsersFordAdvsr.ChabokNotificationPayload.ChabokNotificationActions = actions;

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">اگه مقدار json شده payload رو قرار میدادین بهتر میشد</p>
<p dir="rtl">ولی به بزرگی و کوچیکی حروف دقت کنین
مثلا داخل json مقدار <code>Content</code> نشینه و <code>content</code> قرار بگیره</p>

<blockquote dir="rtl">
<p dir="rtl">در صورتی که سرشماره اس‌ام‌اس خریداری و تنظیم نشده براتون از فراهم اوردن <code>fallback</code> خودداری نمایید</p>
</blockquote>

**Comment by hoseinjamshidi** [comment]
fallback حذف میکنم
این هم json شده کلاس ها


"{\"user\":\"USER_ID\",\"channel\":\"default\",\"Content\":\"مشاور گرامی،شما از لیست مشاوران پیشنهادی خارج شدید.\",\"data\":{},\"trackId\":null,\"inApp\":false,\"live\":false,\"autoNotify\":false,\"useAsAlert\":false,\"alertText\":null,\"ttl\":0.0,\"Myfallback\":null,\"clientId\":null,\"ChabokNotificationPayload\":{\"notificationtitle\":\"اعلان حالت پیشنهادی\",\"body\":\"مشاور گرامی،شما از لیست مشاوران پیشنهادی خارج شدید.\",\"groupId\":null,\"icon\":null,\"sound\":null,\"clickUrl\":null,\"ledColor\":null,\"smallIcon\":null,\"ChabokNotificationActions\":{\"Id\":\"string\",\"Title\":\"اعلان حالت پیشنهادی\",\"Options\":0.0,\"Icon\":null},\"mediaType\":null,\"mediaUrl\":null,\"contentAvailable\":false,\"mutableContent\":false,\"category\":null},\"silent\":false}"

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">همان طور که بالاتر اشاره کردم دقت کنین اسم فیلد ها مطابق <a href="https://api.doc.chabokpush.com/#/push/push_toUsers">داکیومنت</a> باشند</p>
<p dir="rtl">به طورمثال فیلد <code>Content</code> باید به <code>content</code> تغییر پیدا کند</p>
<p dir="rtl"><code>ChabokNotificationPayload</code> به <code>notification</code></p>
<p dir="rtl"><code>ChabokNotificationActions</code> به <code>actions</code></p>
<p dir="rtl">و ....</p>

**Comment by hoseinjamshidi** [comment]
ممون
