### ISSUE TITLE
چگونه بر اساس رفتار، کاربر را به صورت اتوماتیک به یک سگمنت وارد کنم؟

### ISSUE THREAD

**Issue by Hoss3inf** [chabokpush/chabok-panel#48]
سلام. وقت بخیر
در هنگام تعریف سگمنت، رفتاری که کاربر در ایکس ساعت قبل یا ایکس ساعت بعد انجام داده، ملاک وارد کردن یک کاربر به یک سگمنت می شود.
اما این روش برای کمپین خودکار بی مورد است، چون که من باید به صورت دستی، افرادی که رفتار حاصی را انجام داده اند، به سگمنت اضافه کنم، 
لطفا راهنمایی کنید که چگونه سگمنت خودکار ایجاد کنم؟

**Comment by behrad** [comment]
در کمپین‌های خودکار هم شما می تونید از پنچره‌های زمانی پویا در سگمنت‌ها استفاده کنید و ترکیبات پیچیده‌ای داشته باشید
لطفن منظورتون رو از سگمنت خودکار بفرمایید یا اینکه به طور مشخص نیازتون رو به ما بگید
دقیقن راهنمایی کنیم که چطوری کمپین و سگمنت‌تون رو تعریف کنید

**Comment by Hoss3inf** [comment]
ممنون از پاسخ سریع شما.

مشکل م اینه که موقع تعریف کردن کمپین خودکار، نمیدونم چطور همه ی کاربرهایی که از برنامه استفاده می کنند رو توی اون کمپین شرکت بدم. 
وقتی که توی قسمت انتخاب گیرندگان، تب کانال رو انتخاب میکنم که کانال عمومی رو انتخاب کنم، کانالی که شامل همه ی کاربر ها هست، دیگه تو قسمت زمان ارسال، نمیتونم قسمت خودکار رو انتخاب کنم و فقط در لحظه می تونم پوش بفرستم.

زمانی هم که در قسمت انتخاب گیرندگان، بر اساس سگمنت کار می کنم، باید سگمنت جدیدی رو تعریف کنم که بر اساس اون، همه ی اعضا در این سگمنت حضور داشته باشند، اما بلد نیستم همه ی اعضا رو اضافه کنم به اون سگمنت.

اگر ابهامی در مساله ی من وجود داره بفرمایید تا بیشتر توضیح بدم.

**Comment by behrad** [comment]
> مشکل م اینه که موقع تعریف کردن کمپین خودکار، نمیدونم چطور همه ی کاربرهایی که از برنامه استفاده می کنند رو توی اون کمپین شرکت بدم.

به چندین راه می تونید اینکارو بکنید. یک سگمنت تعریف کنید برای کاربرانی که اپ را بیشتر از یک بار بازدید داشته اند
یا سگمنتی که دستگاه کاربر شامل تمام پلتفرم‌ها باشد
یا اگر تمام دستگاهایی را منظور دارید که یک عمل خاص را انجام داده اند، تعداد انجام اون رویداد را بزرگتر از صفر تنظیم کنید



> وقتی که توی قسمت انتخاب گیرندگان، تب کانال رو انتخاب میکنم که کانال عمومی رو انتخاب کنم، کانالی که شامل همه ی کاربر ها هست، دیگه تو قسمت زمان ارسال، نمیتونم قسمت خودکار رو انتخاب کنم و فقط در لحظه می تونم پوش بفرستم.

کانال‌ها برای پیام‌رسانی آنی چابک هستند و در سگمنت و اتومیشن کاربردی ندارند

اگر جواب سوالتون رو نگرفتید بفرمایید توضیح بیشتتر بدیم

**Comment by behrad** [comment]
فقط به نکته مهم توجه داشته باشید که سگمنت‌های چابک پویا (داینامیک) هستند و کاربران در لحظه به آن اضافه می‌شوند یا حذف می‌شوند تا اتومیشن شما درست کار کند

@hamidreza411

**Comment by Hoss3inf** [comment]
> فقط به نکته مهم توجه داشته باشید که سگمنت‌های چابک پویا (داینامیک) هستند و کاربران در لحظه به آن اضافه می‌شوند یا حذف می‌شوند تا اتومیشن شما درست کار کند
> 
> @hamidreza411

این مورد خیلی مهم بود که بدونم. هیچ جای مستندات هم اشاره نشده بود به داینامیک بودن سگمنت ها. حتما اینو به مستندات اضافه کنید.
منوی ساخت سگمنت، بیشتر حس استاتیک بودن رو به سگمنت ها میده. سگمنت و داینامیک بودنشون، خیلی قدرت میده به کاربر برای اجرای کمپین های خوب و اتوماتیک، اما اصلا توانایی ش قابل لمس نیست توی داشبورد.




> به چندین راه می تونید اینکارو بکنید. یک سگمنت تعریف کنید برای کاربرانی که اپ را بیشتر از یک بار بازدید داشته اند
> یا سگمنتی که دستگاه کاربر شامل تمام پلتفرم‌ها باشد
> یا اگر تمام دستگاهایی را منظور دارید که یک عمل خاص را انجام داده اند، تعداد انجام اون رویداد را بزرگتر از صفر تنظیم کنید
> 
لطفا منوی تعریف سگمنت جدید رو مدیریت ش کنید، کار کردن با این منو باید خیلی راحتتر از این حرفا باشه. از همه بیشتر، اون قسمت که ساعت قبل و بعد داره، اصلا سنس نمی کنه. اگر سگمنت داینامیک هست، چرا ساعت قبل و بعد داره؟ نیازی به این کار نیست. اگر من بخام سگمنت تعریف کنم- که بخاد اتوماتیک و داینامیک باشه- باید بتونم بدون این که وابسته به ساعت خاصی باشم، این کار رو انجام بدم. ساعت تعریف کردن بیشتر برای کانال فایده داره که اطلاع رسانی در لحظه یا بازه ی خاص مدنظر هست.

ممنون از راهنمایی تون. تقریبا برام روشن شد که باید چیکار کنم
اگر مشکلی بود باز هم مزاحم تون میشم.

**Comment by behrad** [comment]
> این مورد خیلی مهم بود که بدونم. هیچ جای مستندات هم اشاره نشده بود به داینامیک بودن سگمنت ها. حتما اینو به مستندات اضافه کنید.
> منوی ساخت سگمنت، بیشتر حس استاتیک بودن رو به سگمنت ها میده. سگمنت و داینامیک بودنشون، خیلی قدرت میده به کاربر برای اجرای کمپین های خوب و اتوماتیک، اما اصلا توانایی ش قابل لمس نیست توی داشبورد

@Husseinhj

**Comment by behrad** [comment]
> لطفا منوی تعریف سگمنت جدید رو مدیریت ش کنید، کار کردن با این منو باید خیلی راحتتر از این حرفا باشه. از همه بیشتر، اون قسمت که ساعت قبل و بعد داره، اصلا سنس نمی کنه. اگر سگمنت داینامیک هست، چرا ساعت قبل و بعد داره؟ نیازی به این کار نیست. اگر من بخام سگمنت تعریف کنم- که بخاد اتوماتیک و داینامیک باشه- باید بتونم بدون این که وابسته به ساعت خاصی باشم، این کار رو انجام بدم. ساعت تعریف کردن بیشتر برای کانال فایده داره که اطلاع رسانی در لحظه یا بازه ی خاص مدنظر هست.

در مورد فیدبک اولتون خیلی ممنون و حتمن به مستندات اضافه می کنیم
در مورد این فیدبک، امکان تعریف پنچره زمانی خیلی کاربردی و حیاتی هست برای مارکتر‌ها
اگر شما استفاده‌ای ازش ندارید می تونید به سبک‌دیگه‌ای تعریف کنید سگمنت خودتون رو
اما باید اشاره کنیم که این مدل سگمنتیشن با بررسی چندین سرویس بزرگ دنیا مثل لینپلام، اکسنگیچ ، وب انگیج و ... پیاده سازی شده

فعلن این تاییک رو می بندیم اگه سوالی بود لطفن دوباره باز کنید
