### ISSUE TITLE
ارسال نوتیفیکیشن روی چند دستنگاه

### ISSUE THREAD

**Issue by hoseinjamshidi** [chabokpush/chabok-panel#51]
سلام وقت بخیر برای تست ارسال نوتیفیکیشن ما یک اکانت را روی چند گوشی موبایل باز کردیم و زمانی که با یکی از گوشی ها از اکانت خارج میشویم نوتیفیکیشن برای اون موبایلی که با اکانت مد نظر ما لاگین نیست هم ارسال میشود
برای رفع این مشکل چه راه حلی را پیشنهاد میکنید؟

**Comment by behrad** [comment]
آیا بعد از خارج شدن از اکانت از متد 
`unregister`
 چابک هم استفاده کرده اید؟

**Comment by hoseinjamshidi** [comment]
خیر استفاده نشده است
برای استفاده از این متد باید چه کاری انجام داد؟(داکیومنت مربوطه)

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">برای استفاده از این متد باید چه کاری انجام داد؟(داکیومنت مربوطه)</p>
</blockquote>
<p dir="rtl"><a href="https://doc.chabokpush.com/android/sdk-setup.html#%D8%AD%D8%B0%D9%81-%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1-unregister">مستندات مربوط به unregister کاربر در اندروید</a></p>
