### ISSUE TITLE
ارسال push بعد از unregister کاربر

### ISSUE THREAD

**Issue by hoseinjamshidi** [chabokpush/chabok-panel#52]
سلام وقت بخیر
ما زمانی که کاربر در سامانه unregister  میکنیم تا زمان ورود بعد که در سیستم چابک register بشه اگر در این بازه برای کاربر push ارسال شود بعد از ورود مجدد دریافت نمیکنه و فقط ارسال های بعد از ورود دریافت میکنه
برای رفع این مساله چه راه حلی وجود داره؟؟

**Comment by behrad** [comment]
پیام شما بعلت اینکه کلمات انگلیسی با فارسی مخلوط شده خانا نیست
لطفن بخش انگلیسی رو هم به فارسی بنویسید و ویرایش کنید پیامتون رو تا بتونیم متوجه سوال شما بشیم

**Comment by hoseinjamshidi** [comment]
سلام وقت بخیر
ما زمانی که کاربر در سیستم چابک با استفاده از متد انرجیستر از سیستم حذف میکنیم تا زمان ورود بعد که در سیستم چابک ثبت بشه اگر در این بازه برای کاربر pusنوتیفیکیشن  ارسال شود بعد از ورود مجدد دریافت نمیکنه و فقط ارسال های بعد از ورود دریافت میکنه
برای رفع این مساله چه راه حلی وجود داره؟؟

**Comment by behrad** [comment]
این رفتار طبیعی چابک هست
به طور مثال تلگرام رو فرض کنید، زمانی که شما لاگ اوت می کنید نوتیف نمی گیرید و زمانی که بر میگردید نوتیف‌های بعد از ان رو میگیرید

اگر شما قصد دارید کاربر نوتیف بگیره چرا آنرجیستر می کنید؟

**Comment by hoseinjamshidi** [comment]
چون در زمانی که لاگ اوت میکنه نیازی به دریافت نیست
پس راه حلی وجود نداره که از زمان لاگ اوت(انرجیستر) تا زمان لاگین بعد(رجیستر) نوتیفیکیشن های که توی این بازه ارسال شده که دریافت نکرده با هم دریافت کنه؟

**Comment by behrad** [comment]
> چون در زمانی که لاگ اوت میکنه نیازی به دریافت نیست

وقتی نیازی به دریافت نیست پس چرا بعد از لاگین باید دریافت کنه؟
شما یرای این منظور باید خودتون سمت کسب و کارتون و بکندتون راه کاری پیاده سازی کنید و بعد از رجیستر کردن دوباره پیام‌ها رو بفرستید
این نیاز خاص شما در لایه سرویس‌های موجود پاسخ داده نمیشه

**Comment by hoseinjamshidi** [comment]
ممنون لطف کردید که پاسخ دادید

**Comment by behrad** [comment]
سلامت باشید
اگه باز سوال یا کمکی در این خصوص بود بفرمایید
