### ISSUE TITLE
دریافت نوتیفیکیشن

### ISSUE THREAD

**Issue by hoseinjamshidi** [chabokpush/chabok-panel#54]
سلام وقت بخیر
اگر ما بخوایم در زمان بازبودن نرم افزار موبایل کاربر نوتیفیکیشم های یک بخش خاص دریافت نکنه از چه راهی باید این کارو انجام بدیم؟؟
(مثلا زمانی که کاربر در بخش حسابداری نرم افزار هست نوتیفیکیشان های مربوط به اون بخش دریافت نکنه و نوتیفیکیشن دیگر بخش ها دریافت کنه)

**Comment by hoseinjamshidi** [comment]
سلام وقت بخیر
اگر ما بخوایم در زمان بازبودن نرم افزار موبایل کاربر نوتیفیکیشم های یک بخش خاص دریافت نکنه از چه راهی باید این کارو انجام بدیم؟؟
(مثلا زمانی که کاربر در بخش حسابداری نرم افزار هست نوتیفیکیشان های مربوط به اون بخش دریافت نکنه و نوتیفیکیشن دیگر بخش ها دریافت کنه)

**Comment by behrad** [comment]
وقتی اپلیکیشن کاربر باز هست شما داخل کد می تونید مدیریت کنید نمایش نوتیفیکیشن رو
برای نوتیفیکیشن‌ها داخل جیسان دیتا یا کولپس کی نوع نوتیف رو بگذارید
و اگر کاربر داخل صفحه مورد نظر هست، جلوی نمایش نوتیفیکیشن رو بگیرید

امکان کاستوم کردن نوتیفیکیشن در مستندات چابک موجود است

**Comment by hoseinjamshidi** [comment]
ممنون

**Comment by hoseinjamshidi** [comment]
فقط این کار باید سمت سرور انجام بشه یا در نرم افزار موبایل؟

**Comment by behrad** [comment]
بخش تنظیمات ارسال از سمت سسرور و وب سرویس
بخش مدیریت و کاستوم کردن نوتیفیکیشن داخل نرم افزار موبایل

**Comment by hoseinjamshidi** [comment]
سلام مجدد
برای هندل کردن این مساله کدوم بخش مستندات بای مطالعه بشه؟

**Comment by behrad** [comment]
> برای هندل کردن این مساله کدوم بخش مستندات بای مطالعه بشه؟

@Husseinhj

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">برای هندل کردن این مساله کدوم بخش مستندات بای مطالعه بشه؟</p>
</blockquote>
<p dir="rtl">بخش<a href="https://doc.chabokpush.com/android/push-notification.html#%D8%B4%D8%AE%D8%B5%DB%8C%D8%B3%D8%A7%D8%B2%DB%8C-%D9%86%D9%85%D8%A7%DB%8C%D8%B4-%D9%88-%DA%A9%D9%84%DB%8C%DA%A9-%D8%B1%D9%88%DB%8C-%D8%A7%D8%B9%D9%84%D8%A7%D9%86"> پوش نوتیفیکیشن مستندات اندروید</a></p>

**Comment by hoseinjamshidi** [comment]
در بخش سمت سرور نیازی به تغییر یا ایجاد سرویس خاصی نداره؟
