### ISSUE TITLE
نمایش عنوان

### ISSUE THREAD

**Issue by hoseinjamshidi** [chabokpush/chabok-panel#56]
سلام وقت بخیر
زمانی که نوتیفیکیشن در دیوایس مقصد دریافت میشه این هست که عنوان نوتیفیکیشن هم در بالای نوتیفیکیشن  ارسال نمایش داده میشود هم در پایین نوتیفیکیشن 
به این صورت:
عنوان نوتیفیکیشن 
متن ارسالی
عنوان نوتیفیکیشن 

بین متن ارسالی و عنوان پایین یک خط قرار میگیرد
برای عدم نمایش عنوان در پایین نوتیفیکیشن چکاری باید انجام شود؟

**Comment by Husseinhj** [comment]
Duplicate issue #53
