### ISSUE TITLE
رسیدگی به درخواست پنل عملیاتی

### ISSUE THREAD

**Issue by kamrane** [chabokpush/chabok-panel#6]
سلام
چرا اینقدر طول میکشه؟
چرا شماره تلفن ندادین؟
چرا نه تلگرامی دارین نه چت آنلاین و نه ...؟؟؟

**Comment by amir-yaghoubi** [comment]
<blockquote dir="rtl">
<p dir="rtl">چرا اینقدر طول میکشه؟</p>
</blockquote>
<p dir="rtl">زمان ارسال درخواست و آدرس ایمیل سازمانی خودتون را اعلام کنین تا بررسی کنیم.</p>
<blockquote dir="rtl">
<p dir="rtl">چرا شماره تلفن ندادین؟</p>
</blockquote>
<p dir="rtl">برای ارتباط با ما می‌توانید از طریق ایمیل: <a href="mailto:info@chabok.io">info@chabok.io</a> و یا از طریق github اقدام نمایید.</p>

**Comment by kamrane** [comment]
official.hrd.co@gmail.com

**Comment by amir-yaghoubi** [comment]
اپ آیدی خودتون رو اعلام کنین.
من از شما عذر‌خواهی میکنم، درخواستی برای این ایمیل در سیستم ما ثبت نشده است.
در صورت امکان مجددا درخواست خودتون رو ارسال نمایید.

**Comment by Husseinhj** [comment]
<p dir="rtl">در صورت وجود مشکل مجددا issue را باز کنید</p>
