### ISSUE TITLE
خطا در صفحه ترکر

### ISSUE THREAD

**Issue by ahmadina** [chabokpush/chabok-panel#61]
سلام وقت بخیر
حساب کاربری ما تازه عملیاتی شده . زمانی که به صفحه 
https://panel.push.adpdigital.com/front/tracker
مراجعه کنیم. درخواستی که بصورت ایجکس زده میشه حاوی خطای زیر است
message: "Error from database not found: xxx-tracker-stats"
name: "Error"
status: 500

ممنون میشم راهنمایی کنید

**Comment by behrad** [comment]
سلام
بچه‌ها این موضوع رو فردا برای شما بررسی و رفع می کنند
@amir-yaghoobi

**Comment by amir-yaghoubi** [comment]
به خاطر مشکل پیش‌امده از شما عذرخواهی میکنیم

مشکل برطرف شد براتون.

**Comment by ahmadina** [comment]
وقت بخیر.
مرسی ممنون
