### ISSUE TITLE
سوال درباره ساختار ذخیره سازی کاربر

### ISSUE THREAD

**Issue by ahmadina** [chabokpush/chabok-panel#63]
وقت بخیر

- آیا در چابک میشه آی دی کاربر را تغییر داد؟
مثلا سناریویی را در نظر بگیرید که کاربر وارد اپلیکیشن شده و به عنوان میهمان برایش یک حساب کاربری ساخته میشود و سپس وارد حساب خود میشود آیا راهی هست بتوان آی دی کاربر را بعد از ورود به حساب کاربری مثلا به چیزی مثل شماره موبایل تغییر داد؟

- ما با سناریویی مواجه شدیم که کاربر وارد اپ شده و ثبت نام کرده سپس بدون خروج اقدام به حذف اپ میکند و مجدد با ریتارگت اپ را نصب و وارد اپ میشود ایا در چابک راهی هست که بشه پروفایل این کاربر را یکی نگهداشت؟ 
دلیل بیشتر سوال اولمم برای یوزر آی دی همین بود که بتونیم کاربر را در یک پروفایل یکپارچه نگهداریم 

ممنون میشم راهنمایی کنید

**Comment by behrad** [comment]
درود بر شما
چابک اتفافن با دید ردگیری کاربر طراحی شده و مثل یک موبایل سی‌آر‌ام برای شما عمل می کنه

 

> * مثلا سناریویی را در نظر بگیرید که کاربر وارد اپلیکیشن شده و به عنوان میهمان برایش یک حساب کاربری ساخته میشود

`registerAsGuest(guestID)`



> * سپس وارد حساب خود میشود آیا راهی هست بتوان آی دی کاربر را بعد از ورود به حساب کاربری مثلا به چیزی مثل شماره موبایل تغییر داد؟

`register( USERID (e.g. MOBILE)`



> * ما با سناریویی مواجه شدیم که کاربر وارد اپ شده و ثبت نام کرده سپس بدون خروج اقدام به حذف اپ میکند و مجدد با ریتارگت اپ را نصب و وارد اپ میشود ایا در چابک راهی هست که بشه پروفایل این کاربر را یکی نگهداشت؟

اگر نصب‌ها روی یک دستگاه باشد، خود چابک این موضوع را برای شما هندل می کند

هر دو مورد به سادگی در پیشفرض چابک قابل انجام است.
لطفن تست کنید و اگر رفتار مورد نظر شما صورت نگرفت سوال بپرسید

**Comment by ahmadina** [comment]
من کاربر را به این شکل به صورت میهان در لحظه ورود به اپ در نظر میگیرم و به عنوان میهمان در چابک ثبتش میکنم 
اما مشکلی که هست پس از ورورد کاربر به حساب کاربریش و فراخوانی متد رجیستر و ارسال شماره موبایل به عوان یوز آی دی کاربر جدید ساخته میشود در سیستم و دو دستگاه در چابک ثبت میشود

```   await chabok.getUserId()
                .then(userId => {
                    if (userId) {
                       chabok.register(userId);
                    }
                })
                .catch((e) => {
                    console.log(e);
                    chabok.registerAsGuest();
                });‍‍‍‍```

**Comment by ahmadina** [comment]
و نکته دیگه اینکه در متد ثبت کاربر به عنوان میهمان ورودی برای آی دی وجود ندارد در ری اکت نیتیو و تنها یک حالت را شامل میشود آن هم ایجاد یک کاربر میهمان با آی دی خود چابک بدون گرفتن ورودی از سمت ما

**Comment by behrad** [comment]
> و نکته دیگه اینکه در متد ثبت کاربر به عنوان میهمان ورودی برای آی دی وجود ندارد در ری اکت نیتیو و تنها یک حالت را شامل میشود آن هم ایجاد یک کاربر میهمان با آی دی خود چابک بدون گرفتن ورودی از سمت ما

اگر از نسخه ریکت نیتیو استفاده می کنید، ممکن هست این متد هنوز روی این نسخه نباشد
آقای حبیبی بررسی می کنند اگر نیاز به ثبت دستی آیدی میهمان دارید این قابلیت رو روی ریکت نیتیو اضافه می کنیم
@Husseinhj

**Comment by behrad** [comment]
> ساخته میشود در سیستم و دو دستگاه در چابک ثبت میشود

دستگاه قبلی کاربر پاک خواهد شد
اگر صفحه را رفرش کردید یا بعد از چند دقیقه همچنان باقی بود لطفن برای بررسی بیشتر اپ آیدی و یوزر آیدی این مورد رو در صورت امکان برای ما ارسال کنید تا بتونیم بررسی کنیم.

**Comment by ahmadina** [comment]
> > ساخته میشود در سیستم و دو دستگاه در چابک ثبت میشود
> 
> دستگاه قبلی کاربر پاک خواهد شد
> اگر صفحه را رفرش کردید یا بعد از چند دقیقه همچنان باقی بود لطفن برای بررسی بیشتر اپ آیدی و یوزر آیدی این مورد رو در صورت امکان برای ما ارسال کنید تا بتونیم بررسی کنیم.

درسته اما متاسفانه این اتفاق نمیوفتد و دو کاربر ثبت میشود
info@azinro.com

در پنل جاری دو کاربر وجود دارد که دقیقا با همین شرایط از یک دیوایس هستند

**Comment by behrad** [comment]
> درسته اما متاسفانه این اتفاق نمیوفتد و دو کاربر ثبت میشود

در پنل شما در حال حاضر فقط دو دستگاه وجود دارد با شناسه‌های کاربری و حتی پلتفرم متفاوت و از این حیث دو دستگاه یکسانی وجود ندارد
<img width="800" alt="Screen Shot 1398-06-03 at 16 04 20" src="https://user-images.githubusercontent.com/2151889/63649398-3ca1e780-c752-11e9-9a88-0fcefce5a416.png">

**Comment by ahmadina** [comment]
> > درسته اما متاسفانه این اتفاق نمیوفتد و دو کاربر ثبت میشود
> 
> در پنل شما در حال حاضر فقط دو دستگاه وجود دارد با شناسه‌های کاربری و حتی پلتفرم متفاوت و از این حیث دو دستگاه یکسانی وجود ندارد
> <img alt="Screen Shot 1398-06-03 at 16 04 20" width="800" src="https://user-images.githubusercontent.com/2151889/63649398-3ca1e780-c752-11e9-9a88-0fcefce5a416.png">

پنل پروداکشن ما الان دو دیوایس دیگه رو نشون میده
که یکی از کاربران یوزر آی دی آن با شماره موبایل است
appId: azinro

**Comment by behrad** [comment]
<img width="800" alt="Screen Shot 1398-06-03 at 16 04 20" src="https://user-images.githubusercontent.com/2151889/63649435-d2d60d80-c752-11e9-8a76-96ed45b2200b.png">

مورد اول توی عکس نشان میدهد که یک بار سیمولیتور با گوشی نوع گوگل بیلد گرفته شده یک بار دیگه با گوشی ناشناخته
مورد دوم نشان می‌‌دهد نسخه سیستم عامل اندروید یک بار ۹ بوده یک بار ۵
طبیعتن وقتی با انواع مختلف گوشی بیلد بگیرید چابک نمی تونه دستگاه رو تشخیص بده
اگر روی سیمیلیتور کار می کنید سعی کنید شرایط بیلد رو یکسان نگه دارید

نکته سوم این هست که بیلد میهمان برای چند ساعت پیش و بیلد کاربر برای ۳ روز پیش است 
در حالیکه احتمالن باید برعکس می بود یعنی کاربر اول مهمان میشود بعد کاربر اصلی (وقتی لاگین می کند)

**Comment by ahmadina** [comment]
> <img alt="Screen Shot 1398-06-03 at 16 04 20" width="800" src="https://user-images.githubusercontent.com/2151889/63649435-d2d60d80-c752-11e9-8a76-96ed45b2200b.png">
> 
> مورد اول توی عکس نشان میدهد که یک بار سیمولیتور با گوشی نوع گوگل بیلد گرفته شده یک بار دیگه با گوشی ناشناخته
> مورد دوم نشان می‌‌دهد نسخه سیستم عامل اندروید یک بار ۹ بوده یک بار ۵
> طبیعتن وقتی با انواع مختلف گوشی بیلد بگیرید چابک نمی تونه دستگاه رو تشخیص بده
> اگر روی سیمیلیتور کار می کنید سعی کنید شرایط بیلد رو یکسان نگه دارید
> 
> نکته سوم این هست که بیلد میهمان برای چند ساعت پیش و بیلد کاربر برای ۳ روز پیش است
> در حالیکه احتمالن باید برعکس می بود یعنی کاربر اول مهمان میشود بعد کاربر اصلی (وقتی لاگین می کند)


 فکر میکنم اشتباهی در پنل بررسی شده پیش اومده چون در بخش کاربران پنل ما چنین چیزی رو نشون میده
<img width="856" alt="Screen Shot 2019-08-25 at 4 08 07 PM" src="https://user-images.githubusercontent.com/5356553/63649477-758e8c00-c753-11e9-9446-715fae2e8404.png">

**Comment by behrad** [comment]
> فکر میکنم اشتباهی در پنل بررسی شده پیش اومده چون در بخش کاربران پنل ما چنین چیزی رو نشون میده

کاملن حق با شماست
ما پنل سندباکس شما رو بررسی کردیم با همون ایمیل :)

روی پنل پروداکشن شما، این موضوع وجود داره درسته
فرآیند مدیریت دستگاه‌های کاربر همیشه در کمتر از یک دقیقه عمل می‌کند به استثنا امروز که بطور دستی این فرایند رو با تاخییر اجرا می کنیم

این فرایند در طول امروز تا امشب تمام دستگاه‌های موجود در چابک را به روز خواهد کرد
احتمالن تا عصر یا شب دستگاه قبلی پاک می شود
لطفن مجددن بررسی بفرمایید :)

**Comment by ahmadina** [comment]
> > فکر میکنم اشتباهی در پنل بررسی شده پیش اومده چون در بخش کاربران پنل ما چنین چیزی رو نشون میده
> 
> کاملن حق با شماست
> ما پنل سندباکس شما رو بررسی کردیم با همون ایمیل :)
> 
> روی پنل پروداکشن شما، این موضوع وجود داره درسته
> فرآیند مدیریت دستگاه‌های کاربر همیشه در کمتر از یک دقیقه عمل می‌کند به استثنا امروز که بطور دستی این فرایند رو با تاخییر اجرا می کنیم
> 
> این فرایند در طول امروز تا امشب تمام دستگاه‌های موجود در چابک را به روز خواهد کرد
> احتمالن تا عصر یا شب دستگاه قبلی پاک می شود
> لطفن مجددن بررسی بفرمایید :)

پس با توجه به توضیحاتی که داده شد احتمالا مشکلی نباید وجود داشه باشه و این اتفاق خودش میوفته و فرایند از سمت ما درست طی شده؟

**Comment by behrad** [comment]
مشکلی نیست بله
شما به ظاهر درست پیاده سازی رو انجام دادید

غروب یا فردا زمانی که فرایند حذف انجام شد تست‌های خودتون رو  انجام بدید
اگر موردی بود بفرمایید
