### ISSUE TITLE
مشکل در فعال سازی پوش نوتیفیکیشن

### ISSUE THREAD

**Issue by aliasg** [chabokpush/chabok-panel#8]
با سلام خسته نباشید
ما براساس آموزی های شما بر روی سیستم اندروید پوش نوتیفیکشن رو فعال کردیم اما نمیتوانیم ارسال کنیم و فعال نمیشود درپنل لطفا راهنمایی کنید با تشکر

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">سلام</p>
<p dir="rtl">منظورتون از فعال نمی‌شود. در قسمت تنظیمات پلتفرم‌ها، پلتفرم اندروید به صورت غیر فعال نمایش داده می‌شود؟</p>
<p dir="rtl">اگر این مورد هست، تنظیمات زمانی به حالت فعال در خواهند آمد که شما علاوه بر تنظیم، حداقل یک کاربر بر روی آن پلتفرم رجیستر کرده باشید.</p>
<blockquote dir="rtl">
<p dir="rtl"> اما نمیتوانیم ارسال کنیم </p>
</blockquote>
<p dir="rtl">شما بخش <a href="https://doc.chabokpush.com/android/troubleshoot.html">عیب یابی</a> اندروید را مطالعه نموده‌اید؟</p>
<p dir="rtl">لطفا اطلاعات بیشتری در اختیار بذارین تا راهنمایی کنم (در صورت وجود خطا آن را ارسال کنین)</p>
<p dir="rtl">درصورت امکان <code>appId</code> خودتون رو هم بگین</p>

**Comment by zeoses** [comment]
سلام بنده هم متناسب با کانفیک ها کار ها رو انجام دادم ولی در برنامه هیچ نوتیفیکیشنی دریافت نشد 
و وارنیگ زیر رو در برنامه مشاهده کردم .. .

![dc24](https://user-images.githubusercontent.com/15188675/48536236-2f9ec080-e8c3-11e8-8022-6a96d0a19785.png)

**Comment by behrad** [comment]
@zeoses 
فکر می کنم سوال تون رو در بخش مرتبط نپرسیدید
می تونید در بخش اندروید یا ریکت بپرسید

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">سلام بنده هم متناسب با کانفیک ها کار ها رو انجام دادم ولی در برنامه هیچ نوتیفیکیشنی دریافت نشد</p>
</blockquote>
<p dir="rtl">@zeoses لطفا بفرمایید از کدام کتابخانه ریکت‌نیتو چابک استفاده می‌کنید؟  
<a href="https://github.com/chabokpush/chabok-client-rn-js">react-native pure JS</a> یا <a href="https://github.com/chabokpush/chabok-client-rn">react-native bridge</a></p>

<p dir="rtl">لطفا سوال خودتون رو در repository مرتبط مطرح کنید</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">@aliasg آیا مشکل شما حل شده است؟</p>

**Comment by zeoses** [comment]
> https://github.com/chabokpush/chabok-panel/issues/8#issuecomment-438942806
> https://github.com/chabokpush/chabok-panel/issues/8#issuecomment-438942559

> 

ممنون از راهنماییتون در بخش مربوطه مطرح کردم .. 
آیا سوالم رو از اینجا حذف کنم ... ؟

**Comment by Husseinhj** [comment]
<p dir="rtl">این issue رو می‌بندم چون به repository مرتبط منتقل شده است</p>
