### ISSUE TITLE
ارسال نوتیفیکیشن... هیچ اعلانی دریافت نمی شود

### ISSUE THREAD

**Issue by ehsan-dev** [chabokpush/chabok-panel#9]
سلام... خسته نباشید... بنده تنظیمات پوش چابک را در  اندروید استادیو فعال کردم.. کاربر ثبت نام میشه در پنل چابک کاربر ثبت نام شده قابل نمایش است و همه چی درست کار میکند... اما ارسال پیام روی گوشی کاربر نمایش داده نمی شود.... 
از کتابخانه دیگر استفاده نمیکنیم... تنظیمات گوشی و هر ان جیزی که در دستور العمل نوشتید رعایت شده .. اما همچنان پیام ارسال نمی شود...
راه حلی دارید؟ ممنون

**Comment by Husseinhj** [comment]
<p dir="rtl">آیا بخش <a href="https://doc.chabokpush.com/android/troubleshoot.html#%DB%B1--%D9%BE%D9%88%D8%B4-%D9%86%D9%85%DB%8C%DA%AF%DB%8C%D8%B1%D9%85">عیب‌یابی مستندات اندروید</a> را مطالعه کرده‌اید؟
با مشاهده <a href="https://github.com/chabokpush/chabok-starter-android">پروژه استارتر</a> می‌توانید نمونه کد و نحوه استفاده از چابک را مشاهده کنید.</p>
<blockquote dir="rtl">
<p dir="rtl">ارسال پیام روی گوشی کاربر نمایش داده نمی شود</p>
</blockquote>
<p dir="rtl">هنگامی که اپلیکیشن شما باز است یا اپلیکیشن بسته (kill) است؟</p>
<p dir="rtl">در صورت رخ دادن خطا گزارش خطا در logcat را برای ما اینجا قرار دهید</p>
<blockquote dir="rtl">
<p dir="rtl"><code>نکته</code> : این ریپازیتور برای پشتیبانی پنل می‌باشد. لطفا issue خود را در <a href="https://github.com/chabokpush/chabok-client-android/issues">ریپازیتور اندروید </a>مطرح کنید تا به بقیه توسعه دهنده‌های اندروید برای پیدا کردن پاسخ سوالاتشان بهتره کمک کند.</p>
</blockquote>

**Comment by Husseinhj** [comment]
<p dir="rtl">@ehsan-dev لطفا <code>appId</code> پنل خود را برای ما قرار دهید</p>

**Comment by ehsan-dev** [comment]
امکانش هست یک شماره تماس به ما بدید؟

**Comment by Husseinhj** [comment]
> امکانش هست یک شماره تماس به ما بدید؟

@ehsan-dev در صفحه [تماس با ما](https://chabokpush.com/contact.html) وب‌سایت می‌توانید راه‌های ارتباطی با ما را مشاهده کنید

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">این issue به دلیل نامرتبط بودن با پنل به بخش <a href="https://github.com/chabokpush/chabok-client-android/issues/2#issuecomment-440619572">اندروید</a> منتقل شد.</p>
